# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\ventanas\ventanaMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
sys.path.append(r'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\Bebidas')
import Bebidas_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaMenu(object):
    def setupUi(self, ventanaMenu):
        ventanaMenu.setObjectName("ventanaMenu")
        app = QtWidgets.QApplication([])
        # Obtener la pantalla principal
        screen = app.primaryScreen()

        # Obtener la resolución
        screen_size = screen.size()
        screen_width = screen_size.width()
        screen_height = screen_size.height()
        ventanaMenu.resize(screen_width, screen_height)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventanaMenu.sizePolicy().hasHeightForWidth())
        ventanaMenu.setSizePolicy(sizePolicy)
        ventanaMenu.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(255, 220, 150, 255), /* Color claro, hacia la izquierda */\n"
"        stop:1 rgba(230, 134, 60, 255)  /* Color naranja oscuro, hacia la derecha */\n"
"    );\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(ventanaMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(285, 10, 151, 31))
        self.titulo.setAutoFillBackground(False)
        self.titulo.setStyleSheet("QLabel {\n"
"    font-family: \"Calibri\";         /* Fuente Calibri */\n"
"    font-size: 20pt;                /* Tamaño de 20pt */\n"
"    color: #AC1F01;                 /* Color rojo oscuro especificado */\n"
"    font-weight: bold;            /* Normal, ajusta a bold si necesitas */\n"
"    text-align: left;               /* Alineación izquierda, cámbialo a center si es necesario */\n"
"    background: none;\n"
"}\n"
"")
        self.titulo.setTextFormat(QtCore.Qt.AutoText)
        self.titulo.setOpenExternalLinks(False)
        self.titulo.setObjectName("titulo")
        self.subTitulo = QtWidgets.QLabel(self.centralwidget)
        self.subTitulo.setGeometry(QtCore.QRect(285, 50, 270, 16))
        self.subTitulo.setAutoFillBackground(False)
        self.subTitulo.setStyleSheet("QLabel {\n"
"    font-family: \"Calibri\";         /* Fuente Calibri */\n"
"    font-size: 12pt;                /* Tamaño de 20pt */\n"
"    color: #AC1F01;                 /* Color rojo oscuro especificado */\n"
"    font-weight: bold;            /* Normal, ajusta a bold si necesitas */\n"
"    text-align: left;               /* Alineación izquierda, cámbialo a center si es necesario */\n"
"    background: none;\n"
"\n"
"}\n"
"")
        self.subTitulo.setTextFormat(QtCore.Qt.AutoText)
        self.subTitulo.setOpenExternalLinks(False)
        self.subTitulo.setObjectName("subTitulo")
        self.bJugo = QtWidgets.QPushButton(self.centralwidget)
        self.bJugo.setGeometry(QtCore.QRect(285, 90, 180, 180))
        self.bJugo.setAutoFillBackground(False)
        self.bJugo.setStyleSheet("border-image: url(:/bebidasMenu/bebidasMenu/Jugo.png);\n"
"background: none")
        self.bJugo.setText("")
        self.bJugo.setAutoDefault(False)
        self.bJugo.setDefault(False)
        self.bJugo.setFlat(False)
        self.bJugo.setObjectName("bJugo")
        self.bVodka = QtWidgets.QPushButton(self.centralwidget)
        self.bVodka.setGeometry(QtCore.QRect(495, 90, 180, 180))
        self.bVodka.setStyleSheet("border-image: url(:/bebidasMenu/bebidasMenu/Vodka.png);\n"
"background: none;")
        self.bVodka.setText("")
        self.bVodka.setObjectName("bVodka")
        self.bCachaza = QtWidgets.QPushButton(self.centralwidget)
        self.bCachaza.setGeometry(QtCore.QRect(285, 300, 180, 180))
        self.bCachaza.setStyleSheet("border-image: url(:/bebidasMenu/bebidasMenu/Cachaza.png);\n"
"background: none;")
        self.bCachaza.setText("")
        self.bCachaza.setObjectName("bCachaza")
        self.bRon = QtWidgets.QPushButton(self.centralwidget)
        self.bRon.setGeometry(QtCore.QRect(495, 300, 180, 180))
        self.bRon.setStyleSheet("border-image: url(:/bebidasMenu/bebidasMenu/Ron.png);\n"
"background: none;")
        self.bRon.setText("")
        self.bRon.setObjectName("bRon")
        ventanaMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaMenu)
        QtCore.QMetaObject.connectSlotsByName(ventanaMenu)

    def retranslateUi(self, ventanaMenu):
        _translate = QtCore.QCoreApplication.translate
        ventanaMenu.setWindowTitle(_translate("ventanaMenu", "MainWindow"))
        self.titulo.setText(_translate("ventanaMenu", "¡Bienvenido!"))
        self.subTitulo.setText(_translate("ventanaMenu", "Elija su bebida favorita para comenzar…\n"
""))


