# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\ventanas\ventanaJugo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os

# Asegúrate de que la ruta al archivo .py de recursos sea correcta
sys.path.append(r'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\Bebidas\bebidasJugo')
import bebidasJugo_rc

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaJugo(object):
    def setupUi(self, ventanaJugo):
        ventanaJugo.setObjectName("ventanaJugo")
        ventanaJugo.resize(960, 540)
        ventanaJugo.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(255, 220, 150, 255), /* Color claro, hacia la izquierda */\n"
"        stop:1 rgba(230, 134, 60, 255)  /* Color naranja oscuro, hacia la derecha */\n"
"    );\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(ventanaJugo)
        self.centralwidget.setObjectName("centralwidget")
        self.jPinaCooler = QtWidgets.QPushButton(self.centralwidget)
        self.jPinaCooler.setGeometry(QtCore.QRect(235, 50, 140, 140))
        self.jPinaCooler.setStyleSheet("border-image: url(:/bebidasJugo/pinaCooler.png);\n"
"background: none")
        self.jPinaCooler.setText("")
        self.jPinaCooler.setObjectName("jPinaCooler")
        self.jNaranjaSunrise = QtWidgets.QPushButton(self.centralwidget)
        self.jNaranjaSunrise.setGeometry(QtCore.QRect(405, 50, 140, 140))
        self.jNaranjaSunrise.setStyleSheet("border-image: url(:/bebidasJugo/naranjaSunrise.png);\n"
"background: none;")
        self.jNaranjaSunrise.setText("")
        self.jNaranjaSunrise.setObjectName("jNaranjaSunrise")
        self.jTitulo = QtWidgets.QLabel(self.centralwidget)
        self.jTitulo.setGeometry(QtCore.QRect(240, 10, 461, 40))
        self.jTitulo.setStyleSheet("QLabel {\n"
"    font-family: \"Calibri\";         /* Fuente Calibri */\n"
"    font-size: 14pt;                /* Tamaño de 20pt */\n"
"    color: #AC1F01;                 /* Color rojo oscuro especificado */\n"
"    font-weight: bold;            /* Normal, ajusta a bold si necesitas */\n"
"    text-align: left;               /* Alineación izquierda, cámbialo a center si es necesario */\n"
"    background: none;\n"
"\n"
"}\n"
"")
        self.jTitulo.setObjectName("jTitulo")
        self.jLimonada = QtWidgets.QPushButton(self.centralwidget)
        self.jLimonada.setGeometry(QtCore.QRect(575, 50, 140, 140))
        self.jLimonada.setStyleSheet("border-image: url(:/bebidasJugo/limonada.png);\n"
"background: none;")
        self.jLimonada.setText("")
        self.jLimonada.setObjectName("jLimonada")
        self.jNaranjada = QtWidgets.QPushButton(self.centralwidget)
        self.jNaranjada.setGeometry(QtCore.QRect(235, 210, 140, 140))
        self.jNaranjada.setStyleSheet("border-image: url(:/bebidasJugo/naranjada.png);\n"
"background: none;")
        self.jNaranjada.setText("")
        self.jNaranjada.setObjectName("jNaranjada")
        self.jCitrusPunch = QtWidgets.QPushButton(self.centralwidget)
        self.jCitrusPunch.setGeometry(QtCore.QRect(405, 210, 140, 140))
        self.jCitrusPunch.setStyleSheet("border-image: url(:/bebidasJugo/citrusPunch.png);\n"
"background: none;")
        self.jCitrusPunch.setText("")
        self.jCitrusPunch.setObjectName("jCitrusPunch")
        self.jLimonadaEspumosa = QtWidgets.QPushButton(self.centralwidget)
        self.jLimonadaEspumosa.setGeometry(QtCore.QRect(575, 210, 140, 140))
        self.jLimonadaEspumosa.setStyleSheet("border-image: url(:/bebidasJugo/limonadaEspumosa.png);\n"
"background: none;")
        self.jLimonadaEspumosa.setText("")
        self.jLimonadaEspumosa.setObjectName("jLimonadaEspumosa")
        self.jPinaColada = QtWidgets.QPushButton(self.centralwidget)
        self.jPinaColada.setGeometry(QtCore.QRect(235, 370, 140, 140))
        self.jPinaColada.setStyleSheet("border-image: url(:/bebidasJugo/pinaColada.png);\n"
"background: none;")
        self.jPinaColada.setText("")
        self.jPinaColada.setObjectName("jPinaColada")
        self.vBoton = QtWidgets.QPushButton(self.centralwidget)
        self.vBoton.setGeometry(QtCore.QRect(580, 455, 111, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vBoton.sizePolicy().hasHeightForWidth())
        self.vBoton.setSizePolicy(sizePolicy)
        self.vBoton.setStyleSheet("QPushButton {\n"
"    background-color: #e67e22;\n"
"    color: white;                /* Texto blanco */\n"
"    font-family: Calibri;         /* Fuente Calibri */\n"
"    font-size: 14px;              /* Tamaño de la fuente */\n"
"    font-weight: bold;  \n"
"    border-radius: 10px;          /* Bordes redondeados */\n"
"    padding: 10px 20px;           /* Espaciado interno para agrandar el botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: #d35400;     /* Color de fondo al pasar el mouse */\n"
"}")
        self.vBoton.setObjectName("vBoton")
        ventanaJugo.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaJugo)
        QtCore.QMetaObject.connectSlotsByName(ventanaJugo)

    def retranslateUi(self, ventanaJugo):
        _translate = QtCore.QCoreApplication.translate
        ventanaJugo.setWindowTitle(_translate("ventanaJugo", "MainWindow"))
        self.jTitulo.setText(_translate("ventanaJugo", "Opciones de Vodka disponibles… Seleccione su favorito"))
        self.vBoton.setText(_translate("ventanaJugo", "Volver"))
