# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\ventanas\ventanaCachaza.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
sys.path.append(r'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\Bebidas\bebidasCachaza')
import bebidasCachaza_rc  # Asegúrate de que este archivo existe

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaCachaza(object):
    def setupUi(self, ventanaCachaza):
        ventanaCachaza.setObjectName("ventanaCachaza")
        ventanaCachaza.resize(960, 540)
        ventanaCachaza.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(255, 220, 150, 255), /* Color claro, hacia la izquierda */\n"
"        stop:1 rgba(230, 134, 60, 255)  /* Color naranja oscuro, hacia la derecha */\n"
"    );\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ventanaCachaza)
        self.centralwidget.setObjectName("centralwidget")
        self.cTitulo = QtWidgets.QLabel(self.centralwidget)
        self.cTitulo.setGeometry(QtCore.QRect(240, 10, 461, 40))
        self.cTitulo.setStyleSheet("QLabel {\n"
"    font-family: \"Calibri\";         /* Fuente Calibri */\n"
"    font-size: 14pt;                /* Tamaño de 20pt */\n"
"    color: #AC1F01;                 /* Color rojo oscuro especificado */\n"
"    font-weight: bold;            /* Normal, ajusta a bold si necesitas */\n"
"    text-align: left;               /* Alineación izquierda, cámbialo a center si es necesario */\n"
"    background: none;\n"
"\n"
"}\n"
"")
        self.cTitulo.setObjectName("cTitulo")
        self.cBatidaCitrus = QtWidgets.QPushButton(self.centralwidget)
        self.cBatidaCitrus.setGeometry(QtCore.QRect(575, 210, 140, 140))
        self.cBatidaCitrus.setStyleSheet("border-image: url(:/bebidasCachaza/batidaCitrus.png);\n"
"background: none;")
        self.cBatidaCitrus.setText("")
        self.cBatidaCitrus.setObjectName("cBatidaCitrus")
        self.cCaipifruta = QtWidgets.QPushButton(self.centralwidget)
        self.cCaipifruta.setGeometry(QtCore.QRect(405, 50, 140, 140))
        self.cCaipifruta.setStyleSheet("border-image: url(:/bebidasCachaza/caipifruta.png);\n"
"background: none;")
        self.cCaipifruta.setText("")
        self.cCaipifruta.setObjectName("cCaipifruta")
        self.cCaipirinhaCoca = QtWidgets.QPushButton(self.centralwidget)
        self.cCaipirinhaCoca.setGeometry(QtCore.QRect(405, 210, 140, 140))
        self.cCaipirinhaCoca.setStyleSheet("border-image: url(:/bebidasCachaza/caipirinhaCoca.png);\n"
"background: none;")
        self.cCaipirinhaCoca.setText("")
        self.cCaipirinhaCoca.setObjectName("cCaipirinhaCoca")
        self.cCaipirinha = QtWidgets.QPushButton(self.centralwidget)
        self.cCaipirinha.setGeometry(QtCore.QRect(235, 50, 140, 140))
        self.cCaipirinha.setStyleSheet("border-image: url(:/bebidasCachaza/caipirinha.png);\n"
"background: none")
        self.cCaipirinha.setText("")
        self.cCaipirinha.setObjectName("cCaipirinha")
        self.cCachazaTonic = QtWidgets.QPushButton(self.centralwidget)
        self.cCachazaTonic.setGeometry(QtCore.QRect(575, 50, 140, 140))
        self.cCachazaTonic.setStyleSheet("border-image: url(:/bebidasCachaza/cachazaTonic.png);\n"
"background: none;")
        self.cCachazaTonic.setText("")
        self.cCachazaTonic.setObjectName("cCachazaTonic")
        self.cTropicalCaipirinha = QtWidgets.QPushButton(self.centralwidget)
        self.cTropicalCaipirinha.setGeometry(QtCore.QRect(235, 210, 140, 140))
        self.cTropicalCaipirinha.setStyleSheet("border-image: url(:/bebidasCachaza/tropicalCaipirinha.png);\n"
"background: none;")
        self.cTropicalCaipirinha.setText("")
        self.cTropicalCaipirinha.setObjectName("cTropicalCaipirinha")
        self.cBoton = QtWidgets.QPushButton(self.centralwidget)
        self.cBoton.setGeometry(QtCore.QRect(580, 455, 111, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBoton.sizePolicy().hasHeightForWidth())
        self.cBoton.setSizePolicy(sizePolicy)
        self.cBoton.setStyleSheet("QPushButton {\n"
"    background-color: #e67e22;\n"
"    color: white;                /* Texto blanco */\n"
"    font-family: Calibri;         /* Fuente Calibri */\n"
"    font-size: 14px;              /* Tamaño de la fuente */\n"
"    font-weight: bold;  \n"
"    border-radius: 10px;          /* Bordes redondeados */\n"
"    padding: 10px 20px;           /* Espaciado interno para agrandar el botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: #d35400;     /* Color de fondo al pasar el mouse */\n"
"}")
        self.cBoton.setObjectName("cBoton")
        self.cCachazaCooler = QtWidgets.QPushButton(self.centralwidget)
        self.cCachazaCooler.setGeometry(QtCore.QRect(235, 370, 140, 140))
        self.cCachazaCooler.setStyleSheet("border-image: url(:/bebidasCachaza/cachazaCooler.png);\n"
"background: none;")
        self.cCachazaCooler.setText("")
        self.cCachazaCooler.setObjectName("cCachazaCooler")
        ventanaCachaza.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaCachaza)
        QtCore.QMetaObject.connectSlotsByName(ventanaCachaza)

    def retranslateUi(self, ventanaCachaza):
        _translate = QtCore.QCoreApplication.translate
        ventanaCachaza.setWindowTitle(_translate("ventanaCachaza", "MainWindow"))
        self.cTitulo.setText(_translate("ventanaCachaza", "Opciones de Cachaza disponibles… Seleccione su favorito"))
        self.cBoton.setText(_translate("ventanaCachaza", "Volver"))

