# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\ventanas\ventanaRon.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os

# Asegúrate de que la ruta al archivo .py de recursos sea correcta
sys.path.append(r'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\Bebidas\bebidasRon')
import bebidasRon_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaRon(object):
    def setupUi(self, ventanaRon):
        ventanaRon.setObjectName("ventanaRon")
        ventanaRon.resize(960, 540)
        ventanaRon.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(255, 220, 150, 255), /* Color claro, hacia la izquierda */\n"
"        stop:1 rgba(230, 134, 60, 255)  /* Color naranja oscuro, hacia la derecha */\n"
"    );\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ventanaRon)
        self.centralwidget.setObjectName("centralwidget")
        self.rTitulo = QtWidgets.QLabel(self.centralwidget)
        self.rTitulo.setGeometry(QtCore.QRect(240, 10, 461, 40))
        self.rTitulo.setStyleSheet("QLabel {\n"
"    font-family: \"Calibri\";         /* Fuente Calibri */\n"
"    font-size: 14pt;                /* Tamaño de 20pt */\n"
"    color: #AC1F01;                 /* Color rojo oscuro especificado */\n"
"    font-weight: bold;            /* Normal, ajusta a bold si necesitas */\n"
"    text-align: left;               /* Alineación izquierda, cámbialo a center si es necesario */\n"
"    background: none;\n"
"\n"
"}\n"
"")
        self.rTitulo.setObjectName("rTitulo")
        self.rBoton = QtWidgets.QPushButton(self.centralwidget)
        self.rBoton.setGeometry(QtCore.QRect(585, 440, 111, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rBoton.sizePolicy().hasHeightForWidth())
        self.rBoton.setSizePolicy(sizePolicy)
        self.rBoton.setStyleSheet("QPushButton {\n"
"    background-color: #e67e22;\n"
"    color: white;                /* Texto blanco */\n"
"    font-family: Calibri;         /* Fuente Calibri */\n"
"    font-size: 14px;              /* Tamaño de la fuente */\n"
"    font-weight: bold;  \n"
"    border-radius: 10px;          /* Bordes redondeados */\n"
"    padding: 10px 20px;           /* Espaciado interno para agrandar el botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: #d35400;     /* Color de fondo al pasar el mouse */\n"
"}")
        self.rBoton.setObjectName("rBoton")
        self.rTropicalPunch = QtWidgets.QPushButton(self.centralwidget)
        self.rTropicalPunch.setGeometry(QtCore.QRect(575, 90, 150, 150))
        self.rTropicalPunch.setStyleSheet("border-image: url(:/ bebidasRon/tropicalPunch.png);\n"
"background: none;")
        self.rTropicalPunch.setText("")
        self.rTropicalPunch.setObjectName("rTropicalPunch")
        self.rRonPunch = QtWidgets.QPushButton(self.centralwidget)
        self.rRonPunch.setGeometry(QtCore.QRect(235, 275, 150, 150))
        self.rRonPunch.setStyleSheet("border-image: url(:/ bebidasRon/ronPunch.png);\n"
"background: none;")
        self.rRonPunch.setText("")
        self.rRonPunch.setObjectName("rRonPunch")
        self.rPinaColada = QtWidgets.QPushButton(self.centralwidget)
        self.rPinaColada.setGeometry(QtCore.QRect(235, 95, 150, 150))
        self.rPinaColada.setStyleSheet("border-image: url(:/ bebidasRon/pinaColada.png);\n"
"background: none;")
        self.rPinaColada.setText("")
        self.rPinaColada.setObjectName("rPinaColada")
        self.rCubaLibre = QtWidgets.QPushButton(self.centralwidget)
        self.rCubaLibre.setGeometry(QtCore.QRect(405, 95, 150, 150))
        self.rCubaLibre.setStyleSheet("border-image: url(:/ bebidasRon/cubaLibre.png);\n"
"background: none;")
        self.rCubaLibre.setText("")
        self.rCubaLibre.setObjectName("rCubaLibre")
        self.rRonTonic = QtWidgets.QPushButton(self.centralwidget)
        self.rRonTonic.setGeometry(QtCore.QRect(405, 275, 150, 150))
        self.rRonTonic.setStyleSheet("border-image: url(:/ bebidasRon/ronTonicTropical.png);\n"
"background: none;")
        self.rRonTonic.setText("")
        self.rRonTonic.setObjectName("rRonTonic")
        self.rTropicalCubaLibre = QtWidgets.QPushButton(self.centralwidget)
        self.rTropicalCubaLibre.setGeometry(QtCore.QRect(575, 275, 150, 150))
        self.rTropicalCubaLibre.setStyleSheet("border-image: url(:/ bebidasRon/tropicalCubaLibre.png);\n"
"background: none;")
        self.rTropicalCubaLibre.setText("")
        self.rTropicalCubaLibre.setObjectName("rTropicalCubaLibre")
        ventanaRon.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaRon)
        QtCore.QMetaObject.connectSlotsByName(ventanaRon)

    def retranslateUi(self, ventanaRon):
        _translate = QtCore.QCoreApplication.translate
        ventanaRon.setWindowTitle(_translate("ventanaRon", "MainWindow"))
        self.rTitulo.setText(_translate("ventanaRon", "Opciones de Cachaza disponibles… Seleccione su favorito"))
        self.rBoton.setText(_translate("ventanaRon", "Volver"))
