# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\ventanas\ventanaVodka.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os

# Asegúrate de que la ruta al archivo .py de recursos sea correcta
sys.path.append(r'C:\Users\fredy\Desktop\Estudios\Programacion\Python\PyQt\Bebidas\bebidasVodka')
import bebidasVodka_rc 
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaVodka(object):
    def setupUi(self, ventanaVodka):
        ventanaVodka.setObjectName("ventanaVodka")
        ventanaVodka.resize(960, 540)
        ventanaVodka.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(255, 220, 150, 255), /* Color claro, hacia la izquierda */\n"
"        stop:1 rgba(230, 134, 60, 255)  /* Color naranja oscuro, hacia la derecha */\n"
"    );\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(ventanaVodka)
        self.centralwidget.setObjectName("centralwidget")
        self.tituloVodka = QtWidgets.QLabel(self.centralwidget)
        self.tituloVodka.setGeometry(QtCore.QRect(240, 10, 441, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tituloVodka.sizePolicy().hasHeightForWidth())
        self.tituloVodka.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tituloVodka.setFont(font)
        self.tituloVodka.setStyleSheet("QLabel {\n"
"    font-family: \"Calibri\";         /* Fuente Calibri */\n"
"    font-size: 14pt;                /* Tamaño de 20pt */\n"
"    color: #AC1F01;                 /* Color rojo oscuro especificado */\n"
"    font-weight: bold;            /* Normal, ajusta a bold si necesitas */\n"
"    text-align: left;               /* Alineación izquierda, cámbialo a center si es necesario */\n"
"    background: none;\n"
"\n"
"}\n"
"")
        self.tituloVodka.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tituloVodka.setIndent(2)
        self.tituloVodka.setObjectName("tituloVodka")
        self.vBoton = QtWidgets.QPushButton(self.centralwidget)
        self.vBoton.setGeometry(QtCore.QRect(585, 440, 111, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vBoton.sizePolicy().hasHeightForWidth())
        self.vBoton.setSizePolicy(sizePolicy)
        self.vBoton.setStyleSheet("QPushButton {\n"
"    background-color: #e67e22;\n"
"    color: white;                /* Texto blanco */\n"
"    font-family: Calibri;         /* Fuente Calibri */\n"
"    font-size: 14px;              /* Tamaño de la fuente */\n"
"    font-weight: bold;  \n"
"    border-radius: 10px;          /* Bordes redondeados */\n"
"    padding: 10px 20px;           /* Espaciado interno para agrandar el botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: #d35400;     /* Color de fondo al pasar el mouse */\n"
"}")
        self.vBoton.setObjectName("vBoton")
        self.vDestornillador = QtWidgets.QPushButton(self.centralwidget)
        self.vDestornillador.setGeometry(QtCore.QRect(235, 95, 150, 150))
        self.vDestornillador.setStyleSheet("border-image: url(:/opciones vodka/Destornillador.png);\n"
"background: none;")
        self.vDestornillador.setText("")
        self.vDestornillador.setObjectName("vDestornillador")
        self.vTonic = QtWidgets.QPushButton(self.centralwidget)
        self.vTonic.setGeometry(QtCore.QRect(405, 95, 150, 150))
        self.vTonic.setStyleSheet("border-image: url(:/opciones vodka/Vodka Tonic.png);\n"
"background: none;")
        self.vTonic.setText("")
        self.vTonic.setObjectName("vTonic")
        self.vCaipiroska = QtWidgets.QPushButton(self.centralwidget)
        self.vCaipiroska.setGeometry(QtCore.QRect(575, 95, 150, 150))
        self.vCaipiroska.setStyleSheet("border-image: url(:/opciones vodka/Caipiroska.png);\n"
"background: none;")
        self.vCaipiroska.setText("")
        self.vCaipiroska.setObjectName("vCaipiroska")
        self.vCollins = QtWidgets.QPushButton(self.centralwidget)
        self.vCollins.setGeometry(QtCore.QRect(235, 275, 150, 150))
        self.vCollins.setStyleSheet("border-image: url(:/opciones vodka/vodka collins.png);\n"
"background: none;")
        self.vCollins.setText("")
        self.vCollins.setObjectName("vCollins")
        self.vCitrusPunch = QtWidgets.QPushButton(self.centralwidget)
        self.vCitrusPunch.setGeometry(QtCore.QRect(405, 275, 150, 150))
        self.vCitrusPunch.setStyleSheet("border-image: url(:/opciones vodka/citrus vodka punch.png);\n"
"background: none;")
        self.vCitrusPunch.setText("")
        self.vCitrusPunch.setObjectName("vCitrusPunch")
        self.vLimonCola = QtWidgets.QPushButton(self.centralwidget)
        self.vLimonCola.setGeometry(QtCore.QRect(575, 275, 150, 150))
        self.vLimonCola.setStyleSheet("border-image: url(:/opciones vodka/vodka limon cola.png);\n"
"background: none;")
        self.vLimonCola.setText("")
        self.vLimonCola.setObjectName("vLimonCola")
        self.vCollins.raise_()
        self.tituloVodka.raise_()
        self.vBoton.raise_()
        self.vDestornillador.raise_()
        self.vTonic.raise_()
        self.vCaipiroska.raise_()
        self.vCitrusPunch.raise_()
        self.vLimonCola.raise_()
        ventanaVodka.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaVodka)
        QtCore.QMetaObject.connectSlotsByName(ventanaVodka)

    def retranslateUi(self, ventanaVodka):
        _translate = QtCore.QCoreApplication.translate
        ventanaVodka.setWindowTitle(_translate("ventanaVodka", "MainWindow"))
        self.tituloVodka.setText(_translate("ventanaVodka", "Opciones de Vodka disponibles… Seleccione su favorito"))
        self.vBoton.setText(_translate("ventanaVodka", "Volver"))

